-- 由 gen_grants.py 從 xptltqokykpmiqwlnasm 的實際 ACL 產生，不要手改；改規則請改產生器。
-- 目的：目標 schema 的有效權限＝來源 schema 的有效權限（對 PUBLIC／anon／authenticated／service_role）。
-- 🔴 不可以用 `grant all on all tables/functions` 一句帶過：好日子有 2 個繞過 RLS 的 view 與 4 支
--    security definer 函式在來源是只給 service_role 的，全開等於把會員點數與座位操作對 anon 打開。
-- 驗收：72_grant_parity.py 逐物件×角色比對有效權限。

-- ═══ gooddays（來源 xptltqokykpmiqwlnasm.public）═══
revoke all on schema gooddays from anon;
grant usage on schema gooddays to anon;
revoke all on schema gooddays from authenticated;
grant usage on schema gooddays to authenticated;
revoke all on schema gooddays from service_role;
grant usage on schema gooddays to service_role;
revoke all on SEQUENCE gooddays."order_no_seq" from PUBLIC;
revoke all on SEQUENCE gooddays."order_no_seq" from anon;
revoke all on SEQUENCE gooddays."order_no_seq" from authenticated;
revoke all on SEQUENCE gooddays."order_no_seq" from service_role;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."order_no_seq" to anon;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."order_no_seq" to authenticated;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."order_no_seq" to service_role;
revoke all on SEQUENCE gooddays."quote_no_seq" from PUBLIC;
revoke all on SEQUENCE gooddays."quote_no_seq" from anon;
revoke all on SEQUENCE gooddays."quote_no_seq" from authenticated;
revoke all on SEQUENCE gooddays."quote_no_seq" from service_role;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."quote_no_seq" to anon;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."quote_no_seq" to authenticated;
grant SELECT, UPDATE, USAGE on SEQUENCE gooddays."quote_no_seq" to service_role;
-- （略過 _migrations：目標刻意沒有這個物件）
revoke all on TABLE gooddays."ai_chat_logs" from PUBLIC;
revoke all on TABLE gooddays."ai_chat_logs" from anon;
revoke all on TABLE gooddays."ai_chat_logs" from authenticated;
revoke all on TABLE gooddays."ai_chat_logs" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_chat_logs" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_chat_logs" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_chat_logs" to service_role;
revoke all on TABLE gooddays."ai_usage" from PUBLIC;
revoke all on TABLE gooddays."ai_usage" from anon;
revoke all on TABLE gooddays."ai_usage" from authenticated;
revoke all on TABLE gooddays."ai_usage" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_usage" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_usage" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."ai_usage" to service_role;
revoke all on TABLE gooddays."bookings" from PUBLIC;
revoke all on TABLE gooddays."bookings" from anon;
revoke all on TABLE gooddays."bookings" from authenticated;
revoke all on TABLE gooddays."bookings" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."bookings" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."bookings" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."bookings" to service_role;
revoke all on TABLE gooddays."course_access" from PUBLIC;
revoke all on TABLE gooddays."course_access" from anon;
revoke all on TABLE gooddays."course_access" from authenticated;
revoke all on TABLE gooddays."course_access" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_access" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_access" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_access" to service_role;
revoke all on TABLE gooddays."course_details" from PUBLIC;
revoke all on TABLE gooddays."course_details" from anon;
revoke all on TABLE gooddays."course_details" from authenticated;
revoke all on TABLE gooddays."course_details" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_details" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_details" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_details" to service_role;
revoke all on TABLE gooddays."course_enrollments" from PUBLIC;
revoke all on TABLE gooddays."course_enrollments" from anon;
revoke all on TABLE gooddays."course_enrollments" from authenticated;
revoke all on TABLE gooddays."course_enrollments" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_enrollments" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_enrollments" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_enrollments" to service_role;
revoke all on TABLE gooddays."course_lessons" from PUBLIC;
revoke all on TABLE gooddays."course_lessons" from anon;
revoke all on TABLE gooddays."course_lessons" from authenticated;
revoke all on TABLE gooddays."course_lessons" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_lessons" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_lessons" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."course_lessons" to service_role;
revoke all on TABLE gooddays."membership_tiers" from PUBLIC;
revoke all on TABLE gooddays."membership_tiers" from anon;
revoke all on TABLE gooddays."membership_tiers" from authenticated;
revoke all on TABLE gooddays."membership_tiers" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."membership_tiers" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."membership_tiers" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."membership_tiers" to service_role;
revoke all on TABLE gooddays."order_items" from PUBLIC;
revoke all on TABLE gooddays."order_items" from anon;
revoke all on TABLE gooddays."order_items" from authenticated;
revoke all on TABLE gooddays."order_items" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."order_items" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."order_items" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."order_items" to service_role;
revoke all on TABLE gooddays."orders" from PUBLIC;
revoke all on TABLE gooddays."orders" from anon;
revoke all on TABLE gooddays."orders" from authenticated;
revoke all on TABLE gooddays."orders" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."orders" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."orders" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."orders" to service_role;
revoke all on TABLE gooddays."points_ledger" from PUBLIC;
revoke all on TABLE gooddays."points_ledger" from anon;
revoke all on TABLE gooddays."points_ledger" from authenticated;
revoke all on TABLE gooddays."points_ledger" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."points_ledger" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."points_ledger" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."points_ledger" to service_role;
revoke all on TABLE gooddays."products" from PUBLIC;
revoke all on TABLE gooddays."products" from anon;
revoke all on TABLE gooddays."products" from authenticated;
revoke all on TABLE gooddays."products" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."products" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."products" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."products" to service_role;
revoke all on TABLE gooddays."profiles" from PUBLIC;
revoke all on TABLE gooddays."profiles" from anon;
revoke all on TABLE gooddays."profiles" from authenticated;
revoke all on TABLE gooddays."profiles" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."profiles" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."profiles" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."profiles" to service_role;
revoke all on TABLE gooddays."quotes" from PUBLIC;
revoke all on TABLE gooddays."quotes" from anon;
revoke all on TABLE gooddays."quotes" from authenticated;
revoke all on TABLE gooddays."quotes" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."quotes" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."quotes" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."quotes" to service_role;
revoke all on TABLE gooddays."settings" from PUBLIC;
revoke all on TABLE gooddays."settings" from anon;
revoke all on TABLE gooddays."settings" from authenticated;
revoke all on TABLE gooddays."settings" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."settings" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."settings" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."settings" to service_role;
revoke all on TABLE gooddays."webhook_events" from PUBLIC;
revoke all on TABLE gooddays."webhook_events" from anon;
revoke all on TABLE gooddays."webhook_events" from authenticated;
revoke all on TABLE gooddays."webhook_events" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."webhook_events" to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."webhook_events" to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."webhook_events" to service_role;
revoke all on TABLE gooddays."v_expirable_earn_points" from PUBLIC;
revoke all on TABLE gooddays."v_expirable_earn_points" from anon;
revoke all on TABLE gooddays."v_expirable_earn_points" from authenticated;
revoke all on TABLE gooddays."v_expirable_earn_points" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."v_expirable_earn_points" to service_role;
revoke all on TABLE gooddays."v_user_points_balance" from PUBLIC;
revoke all on TABLE gooddays."v_user_points_balance" from anon;
revoke all on TABLE gooddays."v_user_points_balance" from authenticated;
revoke all on TABLE gooddays."v_user_points_balance" from service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLE gooddays."v_user_points_balance" to service_role;
revoke all on function gooddays.ai_rate_check(p_ip text, p_ip_limit integer, p_global_limit integer) from PUBLIC;
revoke all on function gooddays.ai_rate_check(p_ip text, p_ip_limit integer, p_global_limit integer) from anon;
revoke all on function gooddays.ai_rate_check(p_ip text, p_ip_limit integer, p_global_limit integer) from authenticated;
revoke all on function gooddays.ai_rate_check(p_ip text, p_ip_limit integer, p_global_limit integer) from service_role;
grant EXECUTE on function gooddays.ai_rate_check(p_ip text, p_ip_limit integer, p_global_limit integer) to service_role;
revoke all on function gooddays.confirm_course_seats_for_order(p_order_id uuid) from PUBLIC;
revoke all on function gooddays.confirm_course_seats_for_order(p_order_id uuid) from anon;
revoke all on function gooddays.confirm_course_seats_for_order(p_order_id uuid) from authenticated;
revoke all on function gooddays.confirm_course_seats_for_order(p_order_id uuid) from service_role;
grant EXECUTE on function gooddays.confirm_course_seats_for_order(p_order_id uuid) to service_role;
revoke all on function gooddays.deduct_product_stock(p_items jsonb) from PUBLIC;
revoke all on function gooddays.deduct_product_stock(p_items jsonb) from anon;
revoke all on function gooddays.deduct_product_stock(p_items jsonb) from authenticated;
revoke all on function gooddays.deduct_product_stock(p_items jsonb) from service_role;
grant EXECUTE on function gooddays.deduct_product_stock(p_items jsonb) to service_role;
revoke all on function gooddays.expire_course_reservations() from PUBLIC;
revoke all on function gooddays.expire_course_reservations() from anon;
revoke all on function gooddays.expire_course_reservations() from authenticated;
revoke all on function gooddays.expire_course_reservations() from service_role;
grant EXECUTE on function gooddays.expire_course_reservations() to service_role;
revoke all on function gooddays.handle_new_user() from PUBLIC;
revoke all on function gooddays.handle_new_user() from anon;
revoke all on function gooddays.handle_new_user() from authenticated;
revoke all on function gooddays.handle_new_user() from service_role;
grant EXECUTE on function gooddays.handle_new_user() to service_role;
revoke all on function gooddays.release_course_seats_for_order(p_order_id uuid) from PUBLIC;
revoke all on function gooddays.release_course_seats_for_order(p_order_id uuid) from anon;
revoke all on function gooddays.release_course_seats_for_order(p_order_id uuid) from authenticated;
revoke all on function gooddays.release_course_seats_for_order(p_order_id uuid) from service_role;
grant EXECUTE on function gooddays.release_course_seats_for_order(p_order_id uuid) to service_role;
revoke all on function gooddays.reserve_course_seat(p_product_id uuid, p_user_id uuid, p_order_id uuid, p_confirmed boolean, p_expires_at timestamp with time zone, p_name text, p_email text, p_phone text) from PUBLIC;
revoke all on function gooddays.reserve_course_seat(p_product_id uuid, p_user_id uuid, p_order_id uuid, p_confirmed boolean, p_expires_at timestamp with time zone, p_name text, p_email text, p_phone text) from anon;
revoke all on function gooddays.reserve_course_seat(p_product_id uuid, p_user_id uuid, p_order_id uuid, p_confirmed boolean, p_expires_at timestamp with time zone, p_name text, p_email text, p_phone text) from authenticated;
revoke all on function gooddays.reserve_course_seat(p_product_id uuid, p_user_id uuid, p_order_id uuid, p_confirmed boolean, p_expires_at timestamp with time zone, p_name text, p_email text, p_phone text) from service_role;
grant EXECUTE on function gooddays.reserve_course_seat(p_product_id uuid, p_user_id uuid, p_order_id uuid, p_confirmed boolean, p_expires_at timestamp with time zone, p_name text, p_email text, p_phone text) to service_role;
revoke all on function gooddays.touch_updated_at() from PUBLIC;
revoke all on function gooddays.touch_updated_at() from anon;
revoke all on function gooddays.touch_updated_at() from authenticated;
revoke all on function gooddays.touch_updated_at() from service_role;
grant EXECUTE on function gooddays.touch_updated_at() to PUBLIC;
grant EXECUTE on function gooddays.touch_updated_at() to anon;
grant EXECUTE on function gooddays.touch_updated_at() to authenticated;
grant EXECUTE on function gooddays.touch_updated_at() to service_role;
alter default privileges in schema gooddays revoke all on SEQUENCES from PUBLIC;
alter default privileges in schema gooddays revoke all on SEQUENCES from anon;
alter default privileges in schema gooddays revoke all on SEQUENCES from authenticated;
alter default privileges in schema gooddays revoke all on SEQUENCES from service_role;
alter default privileges in schema gooddays grant SELECT, UPDATE, USAGE on SEQUENCES to anon;
alter default privileges in schema gooddays grant SELECT, UPDATE, USAGE on SEQUENCES to authenticated;
alter default privileges in schema gooddays grant SELECT, UPDATE, USAGE on SEQUENCES to service_role;
alter default privileges in schema gooddays revoke all on FUNCTIONS from PUBLIC;
alter default privileges in schema gooddays revoke all on FUNCTIONS from anon;
alter default privileges in schema gooddays revoke all on FUNCTIONS from authenticated;
alter default privileges in schema gooddays revoke all on FUNCTIONS from service_role;
alter default privileges in schema gooddays grant EXECUTE on FUNCTIONS to anon;
alter default privileges in schema gooddays grant EXECUTE on FUNCTIONS to authenticated;
alter default privileges in schema gooddays grant EXECUTE on FUNCTIONS to service_role;
alter default privileges in schema gooddays revoke all on TABLES from PUBLIC;
alter default privileges in schema gooddays revoke all on TABLES from anon;
alter default privileges in schema gooddays revoke all on TABLES from authenticated;
alter default privileges in schema gooddays revoke all on TABLES from service_role;
alter default privileges in schema gooddays grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLES to anon;
alter default privileges in schema gooddays grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLES to authenticated;
alter default privileges in schema gooddays grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on TABLES to service_role;

-- ═══ gooddays_private（來源 xptltqokykpmiqwlnasm.private）═══
revoke all on schema gooddays_private from anon;
grant usage on schema gooddays_private to anon;
revoke all on schema gooddays_private from authenticated;
grant usage on schema gooddays_private to authenticated;
revoke all on schema gooddays_private from service_role;
grant usage on schema gooddays_private to service_role;
-- （略過 is_admin()：目標刻意沒有這個物件）
